### ISSUE TITLE
Consejo: Formato del codigo

### ISSUE THREAD

**Issue by ivangsa** [Curso-Fullstack-MEAN-Octubre2017/nataCarballo#21]
Es importante mantener el formato correcto, para que luego puedas leerlo y depurarlo

Pregunta: ¿este else sin llaves ni nada funciona correctamente?

https://github.com/Curso-Fullstack-MEAN-Octubre2017/nataCarballo/blob/3dc1bb58c7e832c7300f95b6088992af4a6859e5/public/app/appointmentDetails/appointmentDetails.Component.js#L20

**Comment by ghost** [comment]
Ok a todo, mañana lo formateo.
